# Generated by Django 5.1.1 on 2024-10-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.IntegerField(choices=[(0, "Librarian"), (1, "Member")]),
        ),
    ]
