# Generated by Django 5.1.1 on 2024-10-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_profile_user_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="profile",
        ),
    ]
