# Generated by Django 5.1.1 on 2024-10-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_profile_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table="books",
        ),
        migrations.AlterModelTable(
            name="bookrecords",
            table="book_records",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="profiles",
        ),
    ]
